name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This allows GitHub Actions to push changes

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout the code in the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Set up Node.js
        with:
          node-version: '20'  # Specify the version of Node.js you want to use

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build the React app
        run: npm run build  # No need to set CI in the command
        env:
          CI: false  # Set CI to false once in the environment

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
          publish_dir: ./dist  # Publish the 'build' directory for deployment
          publish_branch: gh-pages  # Ensure it's pushing to gh-pages
